# Generated by Django 3.0 on 2019-12-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='author',
        ),
    ]
