# Generated by Django 3.0 on 2019-12-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20191211_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='Write the description of your listing here.'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='Title of your listing.', max_length=500, unique=True),
        ),
    ]
