# Generated by Django 3.0 on 2019-12-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='username',
        ),
    ]
