from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import User


class Listing(models.Model):
    """ Shows all the listings """
    title = models.CharField(max_length=settings.LISTINGS_TITLE_MAX, unique=True,
                             help_text="Title of your page.")
    link_to_image = models.CharField(max_length=1000, help_text="Add the picture link to your listing.")

    slug = models.CharField(max_length=settings.LISTINGS_TITLE_MAX, blank=True, editable=False,
                            help_text="Unique URL path to access this page. Generated by the system.")
    description = models.TextField(
        help_text="Write the content of your page here.")
    created = models.DateTimeField(auto_now_add=True,
                                   help_text="The date and time this page was created. Automatically generated when the model saves.")
    modified = models.DateTimeField(auto_now=True,
                                    help_text="The date and time this page was updated. Automatically generated when the model updates.")

    # how_long = models.DurationField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """ Getting the url """
        path_components = {'slug': self.slug}
        return reverse('listing-details-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a slug"""
        if not self.pk:
            self.slug = slugify(self.title, allow_unicode=True)

        return super(Listing, self).save(*args, **kwargs)
